### ISSUE TITLE
React does not recognize the `transitionDuration` prop on a DOM element

### ISSUE THREAD

**Issue by ziedHamdi** [TeamWertarbyte/material-auto-rotating-carousel#70] opened 2019-10-29 12:00 UTC
Hi,

I have this error by simply using the lib

```
Warning: React does not recognize the `transitionDuration` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `transitionduration` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(SimpleBackdrop))
    in ForwardRef(SimpleBackdrop) (created by ForwardRef(Modal))
    in div (created by ForwardRef(Modal))
    in ForwardRef(Portal) (created by ForwardRef(Modal))
    in ForwardRef(Modal) (created by AutoRotatingCarousel)
    in AutoRotatingCarousel (created by WithStyles(AutoRotatingCarousel))
    in WithStyles(AutoRotatingCarousel) (created by Query)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Query)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Query)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Query)
    in Query (created by IssueDetail)
    in IssueDetail (created by withRouter(IssueDetail))
    in withRouter(IssueDetail) (created by withI18nextTranslation(withRouter(IssueDetail)))
    in withI18nextTranslation(withRouter(IssueDetail)) (created by WithStyles(withI18nextTranslation(withRouter(IssueDetail))))
    in WithStyles(withI18nextTranslation(withRouter(IssueDetail))) (created by Context.Consumer)
    in ApolloConsumer (created by withApollo(WithStyles(withI18nextTranslation(withRouter(IssueDetail)))))
    in withApollo(WithStyles(withI18nextTranslation(withRouter(IssueDetail)))) (created by ComplaintListView)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ComplaintListView)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Transition)
    in Transition (created by ForwardRef(Zoom))
    in ForwardRef(Zoom) (created by ComplaintListView)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by ComplaintListView)
    in div (created by ComplaintListView)
    in ComplaintListView (created by withRouter(ComplaintListView))
    in withRouter(ComplaintListView) (created by WithStyles(withRouter(ComplaintListView)))
    in WithStyles(withRouter(ComplaintListView)) (created by IssueHome)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by IssueHome)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by IssueHome)
    in IssueHome (created by withRouter(IssueHome))
    in withRouter(IssueHome) (created by WithStyles(withRouter(IssueHome)))
    in WithStyles(withRouter(IssueHome)) (created by Context.Consumer)
    in ApolloConsumer (created by withApollo(WithStyles(withRouter(IssueHome))))
    in withApollo(WithStyles(withRouter(IssueHome))) (created by Detail)
    in div (created by Query)
    in HiddenJs (created by WithWidth(HiddenJs))
    in WithWidth(HiddenJs) (created by Hidden)
    in Hidden (created by Query)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Query)
    in Query (created by SidePanelsInnerLayout)
    in SidePanelsInnerLayout (created by withRouter(SidePanelsInnerLayout))
    in withRouter(SidePanelsInnerLayout) (created by withI18nextTranslation(withRouter(SidePanelsInnerLayout)))
    in withI18nextTranslation(withRouter(SidePanelsInnerLayout)) (created by WithStyles(withI18nextTranslation(withRouter(SidePanelsInnerLayout))))
    in WithStyles(withI18nextTranslation(withRouter(SidePanelsInnerLayout))) (created by Context.Consumer)
    in ApolloConsumer (created by withApollo(WithStyles(withI18nextTranslation(withRouter(SidePanelsInnerLayout)))))
    in withApollo(WithStyles(withI18nextTranslation(withRouter(SidePanelsInnerLayout)))) (created by Detail)
    in div (created by Query)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Query)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Query)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Query)
    in Query (created by ClientLayout)
    in ClientLayout (created by withI18nextTranslation(ClientLayout))
    in withI18nextTranslation(ClientLayout) (created by WithStyles(withI18nextTranslation(ClientLayout)))
    in WithStyles(withI18nextTranslation(ClientLayout)) (created by Context.Consumer)
    in ApolloConsumer (created by withApollo(WithStyles(withI18nextTranslation(ClientLayout))))
    in withApollo(WithStyles(withI18nextTranslation(ClientLayout))) (created by Detail)
    in Detail (created by withRouter(Detail))
    in withRouter(Detail) (created by WithStyles(withRouter(Detail)))
    in WithStyles(withRouter(Detail)) (created by Context.Consumer)
    in ApolloConsumer (created by withApollo(WithStyles(withRouter(Detail))))
    in withApollo(WithStyles(withRouter(Detail))) (created by MyApp)
    in ApolloProvider (created by MyApp)
    in ThemeProvider (created by MyApp)
    in Container (created by MyApp)
    in MyApp (created by withI18nextSSR(MyApp))
    in withI18nextSSR(MyApp) (created by AppWithTranslation)
    in NextStaticProvider (created by withI18nextTranslation(NextStaticProvider))
    in withI18nextTranslation(NextStaticProvider) (created by AppWithTranslation)
    in I18nextProvider (created by AppWithTranslation)
    in AppWithTranslation (created by withRouter(AppWithTranslation))
    in withRouter(AppWithTranslation) (created by withApollo(App))
    in withApollo(App)
    in Suspense
console.<computed> @ main.js?ts=1572350145762:11751
r @ backend.js:6
warningWithoutStack @ react-dom.development.js:506
warning @ react-dom.development.js:2628
validateProperty$1 @ react-dom.development.js:7319
warnUnknownProperties @ react-dom.development.js:7360
validateProperties$2 @ react-dom.development.js:7380
validatePropertiesInDevelopment @ react-dom.development.js:7431
setInitialProperties @ react-dom.development.js:7691
finalizeInitialChildren @ react-dom.development.js:8755
completeWork @ react-dom.development.js:16907
completeUnitOfWork @ react-dom.development.js:19142
performUnitOfWork @ react-dom.development.js:19340
workLoop @ react-dom.development.js:19352
renderRoot @ react-dom.development.js:19435
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
interactiveUpdates$1 @ react-dom.development.js:20495
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
```

**Comment by leMaik** [comment] 2019-12-01 17:00
Duplicate of #67, please update to version 3.0.2

**Closed by leMaik** 2019-12-01 17:00 UTC
